// Code generated by "stringer -type=Retrieve -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RTNode-1]
	_ = x[RTPod-2]
	_ = x[RTNamespace-4]
	_ = x[RTPersistentVolume-8]
	_ = x[RTRBAC-16]
	_ = x[RTService-32]
	_ = x[RTDeployment-64]
	_ = x[RTIngressController-128]
	_ = x[RTEndpoint-256]
}

const (
	_Retrieve_name_0 = "NodePod"
	_Retrieve_name_1 = "Namespace"
	_Retrieve_name_2 = "PersistentVolume"
	_Retrieve_name_3 = "RBAC"
	_Retrieve_name_4 = "Services"
	_Retrieve_name_5 = "Deployment"
	_Retrieve_name_6 = "IngressController"
	_Retrieve_name_7 = "Endpoint"
)

var (
	_Retrieve_index_0 = [...]uint8{0, 4, 7}
)

func (i Retrieve) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Retrieve_name_0[_Retrieve_index_0[i]:_Retrieve_index_0[i+1]]
	case i == 4:
		return _Retrieve_name_1
	case i == 8:
		return _Retrieve_name_2
	case i == 16:
		return _Retrieve_name_3
	case i == 32:
		return _Retrieve_name_4
	case i == 64:
		return _Retrieve_name_5
	case i == 128:
		return _Retrieve_name_6
	case i == 256:
		return _Retrieve_name_7
	default:
		return "Retrieve(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
