// Code generated by "stringer -type=Age"; DO NOT EDIT.

package items

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Equal-0]
	_ = x[Older - -1]
	_ = x[Newer-1]
}

const _Age_name = "OlderEqualNewer"

var _Age_index = [...]uint8{0, 5, 10, 15}

func (i Age) String() string {
	i -= -1
	if i < 0 || i >= Age(len(_Age_index)-1) {
		return "Age(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Age_name[_Age_index[i]:_Age_index[i+1]]
}
