// Code generated by "stringer -type=ObjectType -linecomment"; DO NOT EDIT.

package data

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OTUnknown-0]
	_ = x[OTNode-1]
	_ = x[OTPod-2]
	_ = x[OTNamespace-3]
	_ = x[OTPersistentVolume-4]
	_ = x[OTClusterRole-5]
	_ = x[OTClusterRoleBinding-6]
	_ = x[OTRole-7]
	_ = x[OTRoleBinding-8]
	_ = x[OTService-9]
	_ = x[OTDeployment-10]
	_ = x[OTIngressController-11]
	_ = x[OTEndpoint-12]
}

const _ObjectType_name = "UnknownNodePodNamespacePersistentVolumeClusterRoleClusterRoleBindingRoleRoleBindingServiceDeploymentIngressControllerEndpoint"

var _ObjectType_index = [...]uint8{0, 7, 11, 14, 23, 39, 50, 68, 72, 83, 90, 100, 117, 125}

func (i ObjectType) String() string {
	if i >= ObjectType(len(_ObjectType_index)-1) {
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
