// Code generated by "stringer -type=SourceType -linecomment"; DO NOT EDIT.

package data

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STUnknown-0]
	_ = x[STInformer-1]
	_ = x[STWatchList-2]
	_ = x[STEtcd-3]
}

const _SourceType_name = "UnknownInformerWatchListEtcd"

var _SourceType_index = [...]uint8{0, 7, 15, 24, 28}

func (i SourceType) String() string {
	if i >= SourceType(len(_SourceType_index)-1) {
		return "SourceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SourceType_name[_SourceType_index[i]:_SourceType_index[i+1]]
}
